steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cac-simple-webapp:$COMMIT_SHA', '.']

  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cac-simple-webapp:$COMMIT_SHA']

  # Deploy to Cloud Run as a load balancer service on GKE
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cac-simple-webapp'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cac-simple-webapp:$COMMIT_SHA'
      - '--platform'
      - 'gke'  # Deploy to GKE
      - '--cluster'
      - 'production'  # Replace with your GKE cluster name
      - '--cluster-location'
      - 'us-central1'  # Replace with your GKE cluster location
      - '--namespace'
      - 'green'  # Replace with your Kubernetes namespace
      - '--port'
      - '3000'  # Specify the port to expose

images:
  - 'gcr.io/$PROJECT_ID/cac-simple-webapp:$COMMIT_SHA'
