steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cac-simple-webapp:$COMMIT_SHA', '.']

  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cac-simple-webapp:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cac-simple-webapp'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cac-simple-webapp:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'      # Use a dynamically-set region for flexibility
      - '--allow-unauthenticated'  # Optional: If your app doesn't require authentication
      - '--port'
      - '3000'  # Specify the port to expose

  # Create an external HTTP(S) load balancer
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'compute'
      - 'forwarding-rules'
      - 'create'
      - 'webapp-forwarding-rule'
      - '--region'
      - 'us-central1'
      - '--ports'
      - '3000'
      - '--target-http-proxy'
      - 'webapp-http-proxy'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'compute'
      - 'target-http-proxies'
      - 'create'
      - 'webapp-http-proxy'
      - '--url-map'
      - 'webapp-url-map'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'compute'
      - 'url-maps'
      - 'create'
      - 'webapp-url-map'
      - '--default-service'
      - 'cac-simple-webapp'

images:
  - 'gcr.io/$PROJECT_ID/cac-simple-webapp:$COMMIT_SHA'
