apiVersion: networking.k8s.io/v1
kind: Service
metadata:
  name: cac-simple-webapp
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    matchLabels:
      app: cac-simple-webapp
